import { describe, test, expect, beforeEach, afterEach } from "bun:test"
import { mkdtemp, rm, readFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { existsSync, readdirSync } from "node:fs"
import { generateStream, createGenerateArgs } from "../../src/lib/generate"
import { loadIndex } from "../../src/lib/index"

describe("createGenerateArgs", () => {
  test("creates args with name and repoRoot", () => {
    const args = createGenerateArgs("my-feature", "/repo")
    expect(args).toEqual({
      name: "my-feature",
      repoRoot: "/repo",
    })
  })
})

describe("generateStream", () => {
  let tempDir: string

  beforeEach(async () => {
    tempDir = await mkdtemp(join(tmpdir(), "agenv-test-"))
  })

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true })
  })

  describe("directory structure", () => {
    test("creates correct directory structure", async () => {
      const args = createGenerateArgs("test-feature", tempDir)
      const result = generateStream(args)

      expect(result.streamId).toBe("000-test-feature")
      expect(result.streamPath).toBe("work/000-test-feature")

      const streamDir = join(tempDir, "work", "000-test-feature")
      expect(existsSync(streamDir)).toBe(true)
      expect(existsSync(join(streamDir, "PLAN.md"))).toBe(true)
      expect(existsSync(join(streamDir, "tasks.json"))).toBe(true)
      expect(existsSync(join(streamDir, "files"))).toBe(true)
    })

    test("does not create checklist or principle directories", async () => {
      const args = createGenerateArgs("test-feature", tempDir)
      generateStream(args)

      const streamDir = join(tempDir, "work", "000-test-feature")
      expect(existsSync(join(streamDir, "checklist"))).toBe(false)
      expect(existsSync(join(streamDir, "principle"))).toBe(false)
    })
  })

  describe("PLAN.md generation", () => {
    test("creates PLAN.md with correct header", async () => {
      const args = createGenerateArgs("test-feature", tempDir)
      generateStream(args)

      const planMdPath = join(tempDir, "work/000-test-feature/PLAN.md")
      const content = await readFile(planMdPath, "utf-8")

      expect(content).toContain("# Plan: Test Feature")
      expect(content).toContain("**Stream ID:** 000-test-feature")
      expect(content).toContain("**Created:**")
      expect(content).toContain("**Generated by:**")
    })

    test("creates PLAN.md with all required sections", async () => {
      const args = createGenerateArgs("test-feature", tempDir)
      generateStream(args)

      const planMdPath = join(tempDir, "work/000-test-feature/PLAN.md")
      const content = await readFile(planMdPath, "utf-8")

      // Main sections
      expect(content).toContain("## Summary")
      expect(content).toContain("## References")
      expect(content).toContain("## Stages")

      // Stage subsections
      expect(content).toContain("### Stage 1:")
      expect(content).toContain("#### Stage Definition")
      expect(content).toContain("#### Stage Constitution")
      expect(content).toContain("#### Stage Questions")
      expect(content).toContain("#### Stage Threads")

      // Constitution parts
      expect(content).toContain("**Requirements:**")
      expect(content).toContain("**Inputs:**")
      expect(content).toContain("**Outputs:**")
      expect(content).toContain("**Flows:**")

      // Thread structure
      expect(content).toContain("##### Thread 1:")
      expect(content).toContain("**Summary:**")
      expect(content).toContain("**Details:**")
    })

    test("includes version info", async () => {
      const args = createGenerateArgs("test-feature", tempDir)
      generateStream(args)

      const planMdPath = join(tempDir, "work/000-test-feature/PLAN.md")
      const content = await readFile(planMdPath, "utf-8")

      expect(content).toContain("@agenv/workstreams@")
    })

    test("includes last updated timestamp", async () => {
      const args = createGenerateArgs("test-feature", tempDir)
      generateStream(args)

      const planMdPath = join(tempDir, "work/000-test-feature/PLAN.md")
      const content = await readFile(planMdPath, "utf-8")

      expect(content).toMatch(/\*Last updated: \d{4}-\d{2}-\d{2}\*/)
    })
  })

  describe("tasks.json generation", () => {
    test("creates empty tasks.json", async () => {
      const args = createGenerateArgs("test-feature", tempDir)
      generateStream(args)

      const tasksPath = join(tempDir, "work/000-test-feature/tasks.json")
      const content = await readFile(tasksPath, "utf-8")
      const tasks = JSON.parse(content)

      expect(tasks.version).toBe("1.0.0")
      expect(tasks.stream_id).toBe("000-test-feature")
      expect(tasks.tasks).toEqual([])
      expect(tasks.last_updated).toBeDefined()
    })
  })

  describe("files directory", () => {
    test("creates empty files directory", () => {
      const args = createGenerateArgs("test-feature", tempDir)
      generateStream(args)

      const filesDir = join(tempDir, "work/000-test-feature/files")
      expect(existsSync(filesDir)).toBe(true)

      // Directory should be empty (no README.md)
      const files = readdirSync(filesDir)
      expect(files.length).toBe(0)
    })
  })

  describe("index.json updates", () => {
    test("updates index.json with workstream metadata", async () => {
      const args = createGenerateArgs("test-feature", tempDir)
      generateStream(args)

      const index = loadIndex(tempDir)
      expect(index.streams).toHaveLength(1)
      expect(index.streams[0]?.id).toBe("000-test-feature")
      expect(index.streams[0]?.name).toBe("test-feature")
      expect(index.streams[0]?.path).toBe("work/000-test-feature")
    })

    test("stores version in index metadata", async () => {
      const args = createGenerateArgs("test-feature", tempDir)
      generateStream(args)

      const index = loadIndex(tempDir)
      expect(index.streams[0]?.generated_by.workstreams).toBeDefined()
    })
  })

  describe("workstream ordering", () => {
    test("increments order number for subsequent workstreams", async () => {
      generateStream(createGenerateArgs("first-stream", tempDir))
      generateStream(createGenerateArgs("second-stream", tempDir))
      generateStream(createGenerateArgs("third-stream", tempDir))

      const index = loadIndex(tempDir)
      expect(index.streams[0]?.id).toBe("000-first-stream")
      expect(index.streams[1]?.id).toBe("001-second-stream")
      expect(index.streams[2]?.id).toBe("002-third-stream")
    })
  })

  describe("error handling", () => {
    test("throws on duplicate workstream name", () => {
      const args = createGenerateArgs("test-feature", tempDir)
      generateStream(args)

      expect(() => generateStream(args)).toThrow(
        'Workstream with name "test-feature" already exists'
      )
    })
  })
})
