/**
 * Workstream generation functions
 *
 * Creates workstream directories with PLAN.md and tasks.json files.
 */

import { existsSync, mkdirSync } from "fs"
import { join } from "path"
import type { StreamMetadata, GeneratedBy, TasksFile } from "./types.ts"
import { VERSION as WORKSTREAMS_VERSION } from "../version.ts"
import { getWorkDir } from "./repo.ts"
import {
  getOrCreateIndex,
  saveIndex,
  getNextOrderNumber,
  formatOrderNumber,
  atomicWriteFile,
} from "./index.ts"
import { toTitleCase, getDateString } from "./utils.ts"

/**
 * Generate the version string for templates
 */
function getVersionString(): string {
  return `@agenv/workstreams@${WORKSTREAMS_VERSION}`
}

export interface GenerateStreamArgs {
  name: string
  repoRoot: string
  stages?: number // Number of stages to generate (default: 1)
}

export interface GenerateStreamResult {
  streamId: string
  streamPath: string
}

/**
 * Generate a single stage template
 */
function generateStageTemplate(stageNum: number): string {
  const paddedNum = stageNum.toString().padStart(2, "0")
  return `### Stage ${paddedNum}: <!-- Stage Name -->

#### Stage Definition

<!-- The "what" - what this stage accomplishes -->

#### Stage Constitution

Describe how this stage operates: what it needs (inputs), how it's organized (structure), and what it produces (outputs).

#### Stage Questions

<!-- Unknowns, research to-dos as [ ] checkboxes -->
- [ ]

#### Stage Batches

##### Batch 01: <!-- Batch Name -->

<!-- What this batch accomplishes -->

###### Thread 01: <!-- Thread Name -->

**Summary:**
<!-- Short description of this parallelizable work unit -->

**Details:**
<!-- Any content - implementation notes, dependencies, goals, code examples, etc. -->`
}

/**
 * Generate PLAN.md content with the new structured format
 */
function generatePlanMd(
  streamId: string,
  streamName: string,
  numStages: number = 1,
): string {
  const titleName = toTitleCase(streamName)
  const now = getDateString()
  const version = getVersionString()

  // Generate stage templates
  const stages: string[] = []
  for (let i = 1; i <= numStages; i++) {
    stages.push(generateStageTemplate(i))
  }

  return `# Plan: ${titleName}

> **Stream ID:** ${streamId} | **Created:** ${now} | **Generated by:** ${version}

## Summary

<!-- High-level overview of what this workstream aims to achieve -->

## References

<!-- Source files, reasoning documents, tools used -->

- <!-- Add references here -->

## Stages

${stages.join("\n\n")}

---

*Last updated: ${now}*
`
}

/**
 * Generate empty tasks.json content
 */
function generateTasksJson(streamId: string): TasksFile {
  return {
    version: "1.0.0",
    stream_id: streamId,
    last_updated: new Date().toISOString(),
    tasks: [],
  }
}

/**
 * Main workstream generation function
 *
 * Creates a new workstream with:
 * - PLAN.md at workstream root (structured markdown)
 * - tasks.json at workstream root (empty, populated by add-task)
 */
export function generateStream(args: GenerateStreamArgs): GenerateStreamResult {
  const workDir = getWorkDir(args.repoRoot)

  // Ensure workstreams directory exists
  if (!existsSync(workDir)) {
    mkdirSync(workDir, { recursive: true })
  }

  // Get or create index
  const index = getOrCreateIndex(args.repoRoot)

  // Check if workstream with same name already exists
  const existingStream = index.streams.find((s) => s.name === args.name)
  if (existingStream) {
    throw new Error(
      `Workstream with name "${args.name}" already exists (${existingStream.id})`,
    )
  }

  // Generate stream ID
  const order = getNextOrderNumber(index)
  const streamId = `${formatOrderNumber(order)}-${args.name}`
  const streamPath = `work/${streamId}`
  const streamDir = join(workDir, streamId)

  // Create stream directory
  mkdirSync(streamDir, { recursive: true })

  // Generate PLAN.md
  atomicWriteFile(
    join(streamDir, "PLAN.md"),
    generatePlanMd(streamId, args.name, args.stages ?? 1),
  )

  // Generate empty tasks.json
  atomicWriteFile(
    join(streamDir, "tasks.json"),
    JSON.stringify(generateTasksJson(streamId), null, 2),
  )

  // Create stream metadata (without size)
  const now = new Date().toISOString()
  const generatedBy: GeneratedBy = {
    workstreams: WORKSTREAMS_VERSION,
  }

  const streamMetadata: StreamMetadata = {
    id: streamId,
    name: args.name,
    order,
    size: "medium", // Deprecated - will be removed
    session_estimated: {
      length: 4,
      unit: "session",
      session_minutes: [30, 45],
      session_iterations: [4, 8],
    },
    created_at: now,
    updated_at: now,
    path: streamPath,
    generated_by: generatedBy,
  }

  // Update index
  index.streams.push(streamMetadata)
  saveIndex(args.repoRoot, index)

  return {
    streamId,
    streamPath,
  }
}

/**
 * Create generate args
 */
export function createGenerateArgs(
  name: string,
  repoRoot: string,
  stages?: number,
): GenerateStreamArgs {
  return {
    name,
    repoRoot,
    stages,
  }
}

